language: node_js
node_js:
 - "node"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
global:
  - CODECLIMATE_REPO_TOKEN=fbe4f0a8f24f1c41fe26358fbda2624d740513208c83d5af11540c6a30bf9297
install:
  - npm install
  - createuser user -s -U postgres
  - createdb testdb2 --username=user 
script: "npm test"
after_success:
  - npm run coverage